version: '3.8'
services:
  spring:
    image: public.ecr.aws/${DEV_ECR_REGISTRY_ALIAS}/dev-ecr:${VERSION:-latest}
    environment:
      - VERSION=${VERSION:-latest}
      - SPRING_PROFILES_ACTIVE=dev
    pull_policy: always
    env_file:
      - .env
    depends_on:
      - mysql
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8.0.40
    environment:
      MYSQL_DATABASE: ddingdong
      MYSQL_ROOT_PASSWORD: ${DEV_DB_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    #    volumes:
    #      - mysql-volume:/var/lib/mysql
    volumes:
      - /var/lib/docker/volumes/5c9fc061c8d4a72682f54b0bed465f9e91efa0039bd031937479516888b5f872/_data:/var/lib/mysql

volumes:
  mysql-volume:
