version: '3.7'

services:

  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    environment:
      - LOKI_URL=${LOKI_URL}  # .env 파일에서 Loki 서버 URL 참조
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
      - ./logs:/var/log  # 로컬 로그 파일 경로를 Promtail에 마운트
    command: -config.file=/etc/promtail/config.yml
    ports:
      - "9080:9080"  # Promtail의 웹 UI를 호스트와 매핑
