spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}

  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
    defer-datasource-initialization: false

  sql:
    init:
      mode: never

jwt:
  header: "Authorization"
  prefix: "Bearer"
  issuer: "ddingdong"
  secret: ${JWT_SECRET}
  expiration: 36000
