spring:
  config:
    activate:
      on-profile: local

  flyway:
    enabled: false

  datasource:
    url: jdbc:mysql://localhost:3307/ddingdong_local_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
    defer-datasource-initialization: false

  sql:
    init:
      mode: always
